language: php

php:
  - 7.0
  - 7.1
  - 7.2

addons:
  code_climate:
    repo_token: a31c1e81b54f4e08504f115d84e1d91ae631e6eb30d32420434ac846d24d7aa9

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit